#!/usr/bin/env python3
"""update_progress.py - regenerate PROGRESS.md from config/tasks.json.

The human-readable progress tracker is generated from the machine-readable
registry so the two can never drift. Run: python3 harness/update_progress.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def box(s):
    return {"done": "[x]", "running": "[~]", "blocked-on-human": "[H]",
            "blocked-on-hardware": "[M]", "pending": "[ ]", "failed": "[!]",
            "deferred": "[<bus>]"}[s]


def main() -> int:
    d = json.loads((ROOT / "config" / "tasks.json").read_text())
    L = []
    L.append("# PROGRESS — Qwen3.8-Flash-Next on 4× MI50 (gfx906)")
    L.append("")
    L.append("Work Order **Rev 5** (supersedes Rev 4; invariants I1-I10 carry forward). This file is the")
    L.append("human-readable progress tracker; `config/tasks.json` is the machine-readable source of truth")
    L.append("(this page is generated by `harness/update_progress.py`).")
    L.append("")
    L.append("**Key:** [x] done · [~] in progress · [H] blocked on operator · [M] blocked on hardware · [ ] pending")
    L.append("")
    # The narrative status section used to be hand-maintained, which drifted from
    # config/tasks.json AND was silently deleted by every regeneration. It now comes
    # from the registry like everything else.
    su = d.get("status_update")
    if su:
        as_of = su.get("as_of", "")
        L.append(f"## Current status update ({as_of})" if as_of else "## Current status update")
        L.append("")
        for bullet in su.get("bullets", []):
            L.append(f"- {bullet}")
        L.append("")
    L.append("## Gates")
    L.append("")
    L.append("| Gate | When | Predicate | Status |")
    L.append("|---|---|---|---|")
    for g in d["gates"]:
        L.append(f"| {g['id']} | {g['when']} | {g['predicate']} | {g['status']} |")
    L.append("")
    L.append("## Track N — now (single-GPU, before cards)")
    L.append("")
    for lane, title in [("N-A", "host changes requiring reboots [HUMAN]"), ("N-B", "toolchain"),
                        ("N-C", "repo mining"), ("N-D", "wave64 ports to correctness"),
                        ("N-E", "single-card measurements")]:
        L.append(f"### Lane {lane} — {title}")
        L.append("")
        L.append("| Task | Status | Evidence / notes |")
        L.append("|---|---|---|")
        for t in d["tasks"]:
            if t["id"].startswith(lane):
                L.append(f"| {t['id']} | {box(t['status'])} {t['status']} | {t.get('progress', '')} |")
        L.append("")
    L.append("## Track M — four-card day-one bring-up")
    L.append("")
    L.append("| Task | Status | Evidence / notes |")
    L.append("|---|---|---|")
    for t in d["tasks"]:
        if t["id"].startswith("M"):
            L.append(f"| {t['id']} | {box(t['status'])} {t['status']} | {t.get('progress', '')} |")
    L.append("")
    L.append("## Track O — optimization (after M4 only)")
    L.append("")
    L.append("| Task | Status | Notes |")
    L.append("|---|---|---|")
    for t in d["tasks"]:
        if t["id"].startswith("O"):
            L.append(f"| {t['id']} | {box(t['status'])} {t['status']} | {t.get('progress', '')} |")
    L.append("")
    # Track P: the TP8 feasibility probe (D150). Added because the generator only rendered the N, M
    # and O prefixes, so these tasks were invisible in PROGRESS.md even though they existed in
    # config/tasks.json - the machine-readable source of truth and the human page disagreed.
    L.append("## Track P — TP8 feasibility probe (D150)")
    L.append("")
    L.append("| Task | Status | Notes |")
    L.append("|---|---|---|")
    for t in d["tasks"]:
        if t["id"].startswith("TP8"):
            L.append(f"| {t['id']} | {box(t['status'])} {t['status']} | {t.get('progress', '')} |")
    L.append("")
    L.append("## Human decisions (H1-H8)")
    L.append("")
    for hid, h in d["decisions"].items():
        L.append(f"- **{hid}** — {h}")
    L.append("")
    L.append("## STOP conditions")
    L.append("")
    for s in d["stops"]:
        L.append(f"- **{s['id']}** ({s['task']}): {s['condition']} — not triggered")
    L.append("")
    L.append("## Where we are")
    L.append("")
    L.append("- **Gates passed:** G0, G1, G2; G2.2 single-GPU portion closed with residual to M0.7 [ABS].")
    L.append("  G3 (peer write) = M0 determination, pending cards.")
    L.append("- **Single-GPU phase COMPLETE (D027-D078):** Lane D wave64 ports; port tree builds and")
    L.append("  validates in-tree (dense/fused/MoE); PLE sidecar validated + protocol proven live;")
    L.append("  surrogate built + serves; T1/T3 pass (boundary flip at tok 14, D055); T2 documented;")
    L.append("  N-E4 graph ratio ~3.3x correct (compile OFF on gfx906 - inductor miscompile, D060);")
    L.append("  N-E7 routing skew ~1.28 wait ratio (D065); N-E8 fixed-cost floor ~15-20us (D066);")
    L.append("  MoE triton backend verified (D067); ceiling corrected to ~810 GB/s (D044).")
    L.append("- **Switch path (D068-D078):** PEX88096 installed - x8x8 slot mode required (D077),")
    L.append("  ACS enabled but overridable (STOP-A provisional, D073 - setpci clear + systemd unit),")
    L.append("  per-port IOMMU groups confirmed; MI50 Gen3 x16 (its max); host<->GPU 14 GB/s;")
    L.append("  x8x8 + Gen3 quantified as non-issues for the targets (D078).")
    L.append("- **Pre-cards prep:** M-track harness ready (run_m0.sh), tp4_rank0 scaffolded, 96 GB floor")
    L.append("  explained (D064), D049 closed (D044).")
    L.append("- **D066/D079 done:** fused poll+reduce kernel validated at 1.85 us/step (5.6x cut).")
    L.append("- **Post-flash (D088-D096):** card flashed to the V420 MI50 ROM - Gen4 (66A0),")
    L.append("  superseding D078's Gen3 framing; raw ceiling ~unchanged (D092); 27B +25% is")
    L.append("  pattern-specific (re-derive Flash-Next at M4); N-C8 LDS ladder + N-C9 capability")
    L.append("  banner both done; M5 = MTP x context sweep (D094); Track O adds O7/O8 (D094).")
    L.append("- **Two cards live (D103-D105, 2026-09-06):** a SECOND post-flash MI50/V420 is in <vm>")
    L.append("  (guest <pci>/renderD129; host <pci> on port <pci>); both cards at H1 150 W.")
    L.append("  D103 measured NO guest-visible device P2P on the default topology (cross")
    L.append("  canAccessPeer=0, EnablePeerAccess fails, hipIpcOpenMemHandle fails; hipMemcpyPeer")
    L.append("  ~6.2 GB/s host bounce) - QEMU presents each GPU behind its own root port, so the")
    L.append("  switch is invisible in-guest. D104 deep-dive: kernel P2P support is present")
    L.append("  EVERYWHERE (PCI_P2PDMA/HSA_AMD_P2P=y on <vm> AND <source-host>; amdgpu.pcie_p2p=Y); the")
    L.append("  D103 'RCCL segfault' was a 7.2.4/7.14 libamdhip64 runtime mix - RCCL 2-dev")
    L.append("  all_reduce WORKS on a consistent 7.14 runtime (~63 us/op 20 KB, host path,")
    L.append("  bit-exact); and under an emulated x3130 switch pci_p2pdma_distance = 4 both")
    L.append("  directions (kernel probe) BUT KFD p2p links stayed empty (UBSAN bug in")
    L.append("  amdgpu_amdkfd_get_pcie_bandwidth_mbytes suspect - unconfirmed). Incident: the")
    L.append("  GPUs PSP-wedged mid-experiment; a <source-host> power cycle cleared it (D105) and the box")
    L.append("  is healthy on the restored hostpci config (<vm> + llama service up). Transport")
    L.append("  direction = operator decision (multifunction retest / host-staged RCCL / LXC).")
    L.append("- **D106 (2026-09-06):** UBSAN root cause CONFIRMED from the persisted kern.log -")
    L.append("  'shift exponent -1 is negative' at amdgpu_amdkfd.c:604 = zero pcie_mlw/gen masks")
    L.append("  (passthrough skips the default-mask assignment; the emulated switch yields no")
    L.append("  partner caps). Fix ready: amdgpu.pcie_gen_cap/pcie_lane_cap module params (or an")
    L.append("  HWE guest kernel) - one cmdline change + clean reboot, no in-guest rmmod.")
    L.append("  RCCL 2-rank all_reduce curve banked (~56 us fixed overhead; 20 KB = 77.4 us):")
    L.append("  option (b) collapses to 7.14-runtime RCCL + --disable-custom-all-reduce as a")
    L.append("  de-risking FLOOR, but 4-rank projection (95-160 us/op) misses G6 - P2P stays")
    L.append("  worth one more shot. Multifunction variant dropped (failure is link caps, not")
    L.append("  ancestry); LXC on <source-host> is the fallback if the params/HWE attempt fails.")
    L.append("- **D107 (2026-09-06):** step-3 run - the params FIXED the UBSAN/io-link fill under")
    L.append("  the emulated switch and pci_p2pdma_distance=4 held, but p2p links stayed empty.")
    L.append("  THE FINAL GATE found: gfx906's 44-bit dma_mask cannot cover the guest BARs that")
    L.append("  OVMF/Proxmox q35 places at <bar-addr> (~2^46) - the BAR-vs-mask term of")
    L.append("  amdgpu_device_is_peer_accessible fails, independent of topology. Host-side the")
    L.append("  same BARs sit at ~2^39 (< 2^44), so LXC/bare-metal on <source-host> passes every gate.")
    L.append("  hole64-start is read-only (-global rejected); not a stock knob. Recommendation:")
    L.append("  G3/P2P measurement via LXC on <source-host>; box restored to the stable hostpci config,")
    L.append("  healthy.")
    L.append("- **D108/D109 (2026-09-06):** LXC path on <source-host> - host KFD p2p links WORK (canAccessPeer=1,")
    L.append("  EnablePeerAccess OK - the first time peer capability has ever been enabled). Kernel")
    L.append("  peer STORES poison the writer GPU on gfx906 (D108 wedge; <source-host> power cycle cleared")
    L.append("  it), but the SDMA peer-COPY path is clean: D109 measured 28.5 GB/s symmetric 0<->1")
    L.append("  at 256 MB (byte-exact, ~90% of the Gen4 x16 ceiling, beats the fork's 14.3/5.7) -")
    L.append("  G3 answered on the host path. M2 should adopt copy-based peer transport; the")
    L.append("  deployment/transport decision (LXC vs VM) is now the binding question.")
    L.append("- **D110 (2026-09-06):** follow-ups - SDMA peer-COPY latency at the decode operating point:")
    L.append("  20 KB = 11.8 us/op (floor ~11.2 us dispatch), the G5-relevant number (NOT the 28.5 GB/s")
    L.append("  bandwidth). 28.5 GB/s = 1.8x the x8-Gen4 upstream one-way ceiling -> provably switch-")
    L.append("  internal. KERNEL-STORE VERDICT REVERSED: UNCACHED staging works byte-exact (default")
    L.append("  cached hipMalloc was the D108 poison source - memory type, so the fork's AR shape + D079")
    L.append("  fused worker are viable). N-E3 re-probed: q=2 = 1.89x on the host (VFIO flatness was an")
    L.append("  artifact). D037 partial: IPC opens cross-GPU on the host but naive handoff segfaults")
    L.append("  (fork protocol needed). Record corrections: phys-bits (46-bit) is the stock lever for")
    L.append("  D107's BAR placement; ACS D073/D074 PROVISIONAL -> RESOLVED.")
    L.append("- **D111/D112 (2026-09-06):** STACK VALIDATION on the host/LXC path PASSED - the full")
    L.append("  surrogate stack (<vm> venv + port tree + surrogate + PLE sidecar, bind-mounted into")
    L.append("  LXC <ct>, no rebuild) serves on the host GPUs: single-GPU reproduces the golden exactly")
    L.append("  through token 14 then the documented boundary flip (D111); TP2 across the 2 host GPUs")
    L.append("  WORKS (first multi-GPU TP run of the port anywhere - EP dispatch + TP comms + per-rank")
    L.append("  PLE offload; golden-like output, flip ~tok 11 = TP fp16 rounding; D112). In-situ eager")
    L.append("  per-layer anchor 2.69 ms/layer incl. collectives+PLE (46.5 tok/s, batch-4 118 tok/s).")
    L.append("  Container env fixes: python3-dev, amdsmi-preinit sitecustomize, 40 GB RAM (8 GB")
    L.append("  OOM-killed a TP worker - the PLE prefault + 2 workers need >8 GB).")
    L.append("- **D113 (2026-09-06):** per-layer anchor DECOMPOSED - at TP2 eager: per_layer 2.35 ms,")
    L.append("  fixed 2.7 ms/step (4L vs 8L runs; naive 2.69 ms/layer overstated ~14%). Scaling")
    L.append("  TP1->TP2 (same day, eager 8L): 66.5 vs 46.5 tok/s = 0.70x - NEGATIVE at surrogate")
    L.append("  scale (small-model TP penalty). Graph factor at TP2: 2.9x (133 tok/s). 48L eager")
    L.append("  projection ~115 ms/token at TP2-width; TP2->TP4 scaling remains the dominant")
    L.append("  uncertainty and now looks worse than clean halving. RAM: TP2 needed 40 GB in the")
    L.append("  container; TP4 ~46-50 GB collides with any llama-in-LXC plan (deployment decision).")
    L.append("- **D114 (2026-09-06):** DECISION - LXC/host on <source-host> is THE deployment target; the")
    L.append("  VFIO-guest option is DROPPED (closed on merit, D107); the transport decision is")
    L.append("  CLOSED; M0/M0.7/M1/M2 host-path items are UNBLOCKED (2 cards) - only 4-card")
    L.append("  completion stays [M]. llama has no home during M2-M4 (RAM arithmetic, D113).")
    L.append("- **D115 (2026-09-06):** Step-1 kernel/bubble probe - ~50 kernels/layer (~2,400/step")
    L.append("  at 48L; torch-native elementwise = 43% of launches (the gfx906 residue); fused glue")
    L.append("  IS firing (1,050 launches); dispatch bubble ~7.7 ms/token eager (~19 us x ~410")
    L.append("  kernels/token) removed by graphs - LAUNCH-BOUND confirmed at model level.")
    L.append("- **D116 (2026-09-06):** 48L TP2 attempt - exact VRAM deficit recorded (OOM at")
    L.append("  ~36.5 GB/rank vs 32 GB/card, no offload) + second blocker: the PLE worker cannot")
    L.append("  load the full-model weight layout. Surrogate profile is the baseline per timebox.")
    L.append("- **D117 (2026-09-06):** M2 AR VALIDATED on the 2 real host GPUs - the wave64 one-shot")
    L.append("  all-reduce (fork T44 protocol) = 30.7 us/op @ 20 KB world=2, CORRECT (under the fork")
    L.append("  33 us target / G5 34 us budget). hipIpcOpenMemHandle asymmetry finding recorded for")
    L.append("  the multi-process wiring.")
    L.append("- **D118-D121 (2026-09-06):** Step-2 measured to a verdict - gfx906 ~50 kernels/layer")
    L.append("  vs fork 37 (gap real); the named T46 pieces are NOT the lever: fused glue fires,")
    L.append("  norms + QSA are ALREADY triton-fused (layer_norm_fwd, _qsa_*; D115's HIP-vs-Triton")
    L.append("  split corrected - triton is name-hidden), and forcing the vllm_c norm priority")
    L.append("  changed nothing (identical counts, D121). Residual gap = the ~22 torch-elementwise")
    L.append("  launches/layer; next action = trace_attr.py frame attribution, then fuse the largest")
    L.append("  sites on a writable tree.")
    L.append("- **D132 (2026-09-06):** 48L graphs profile (D131 runbook): dense_gemv = 53.7% of GPU")
    L.append("  time, fused_glue 26.9%, moe_int4 13.2%, torch_elem <1% - the torch-elem fusion thread")
    L.append("  was attacking <1% of GPU time (wrong lever, confirmed); dense is offload-inflated ~20x")
    L.append("  (UVA zero-copy fetch inside the gemv kernels); N-D5 int8 dense targets the 54% term.")
    L.append("- **D133-D136 (2026-09-06):** Task 1 kernel microbenchmark COMPLETE - dense GEMV 12-shape")
    L.append("  M4 sum 0.704ms vs V620 1.43ms (~2.0x MI50; lm_head 451us vs 1.28ms fp16 = 2.84x, beats")
    L.append("  V620 int8 640us); fused glue bandwidth-bound M-invariant (gemv_act 61us, hc_mix 158us,")
    L.append("  se_gu 36us, se_dn 46us); MoE w13+w2 pair 109us @M=1 vs V620 98us (1.11x, near-parity);")
    L.append("  QSA/GDN negligible (0.3-0.5% each). VERDICT: dense+glue (~81% GPU time) MI50-favored,")
    L.append("  MoE near-parity -> gfx906 MTP0 parity ACHIEVABLE on the measured terms; N-D5 rationale")
    L.append("  weakened (gfx906 fp16 already beats V620 int8). G6 60-62 t/s MTP0 stays on the table.")
    L.append("- **D137 (2026-09-06):** End-to-end token accounting - W = 393.84 ms/token (2.54 tok/s,")
    L.append("  48L TP2 graphs+offload, median of 3). FINDING: the independent GPU-busy signal is")
    L.append("  UNAVAILABLE on the flashed V420 cards (rocm-smi --showuse AND gpu_busy_percent read 0")
    L.append("  even under a verified saturating load) - the Case A/B discriminator's hardware leg cannot")
    L.append("  pass. K/W ~91% (profiler, D132 trace) -> provisional Case A, ~8.6% residual; PLE/CPU")
    L.append("  phases unmeasured (fork-instrumentation not done). ENV: vLLM:: prctl-named processes leak")
    L.append("  GPU memory past pkill -f python3 - clients must llm.shutdown(). 60-62 t/s remains")
    L.append("  plausible-but-unproven; the offload-inflated dense bucket (~49% of wall) needs cards 3-4.")
    L.append("- **D138 (2026-09-06):** D137 verdict refined to OFFLOAD-STALL DOMINANT. Three-piece chain:")
    L.append("  D133 resident dense GEMV is excellent (816 GB/s); D132 offload inflates dense ~20x")
    L.append("  (~193 vs ~9.5 ms/token); D137 that inflated family = ~49% of the 393.84 ms/token wall.")
    L.append("  'gfx906 arithmetic is slow' is untenable; weight offload is THE bottleneck. K/W ~91%")
    L.append("  = long-lived kernel intervals (no large between-replay idle bubble). PLE unmeasured and")
    L.append("  deferred (not material to this ranking). Eager->graphs 3.53x = launch removed, offload")
    L.append("  stall kept. Implied TP2 fix: ~210 ms/token ~ 4.75 tok/s (~1.87x). CARDS 3-4 (128 GB,")
    L.append("  fully resident, TP4) are the next experiment - only then is the V620 TP4 comparison")
    L.append("  meaningful; 25-30 t/s from TP2 must not be read as an MI50 silicon estimate. TRAPS.md")
    L.append("  created (prctl process leak, spawn main-guard, silent RO-mount pushes, dead SM-busy")
    L.append("  counter, ignore_eos, awk field, heredoc newlines).")
    L.append("- **CARDS ARRIVED — four-card TP4 is LIVE on <host> (D139-D143).** Everything above")
    L.append("  this line is pre-cards history. Current state:")
    L.append("  * **Phase 1 (M0/M0.7) DONE** - 12/12 ordered peer pairs byte-exact at 14.40-14.44 GB/s,")
    L.append("    Gen4 x16 end-to-end, ACS auto-cleared on 11 GPU-path bridges at boot; peer-BAR")
    L.append("    payload->fence->arrive->flag ordering validated 12/12 x 120 reps. Caveat: the test")
    L.append("    cannot falsify the hardware-reorder hazard (controls are also clean), so it proves the")
    L.append("    protocol works here, NOT that the fence is load-bearing. Keep the fence.")
    L.append("  * **Phase 2 (M1/M2) DONE** - RCCL world=4 floor 106.96 us @ 20 KB (inside D106's")
    L.append("    projection); custom wave64 one-shot AR at world=4 = 70.34 us, correct, bit-identical,")
    L.append("    and GRAPH REPLAY PASS (device-derived seqbuf advanced exactly).")
    L.append("  * **Phase 3 (M3) DONE** - TP4 fully resident: 18.23 GiB/rank x 4 = 72.9 GiB, **no weight")
    L.append("    offload**, MTP=0, fp16, graphs-no-compile (compile OFF per D060), PLE from the int4")
    L.append("    sidecar. Deterministic greedy output. Cold load 72.7 s from NVMe.")
    L.append("  * **Phase 4 (M4) DONE** - TP4 profile captured in-engine; attribution ACCEPTED")
    L.append("    (per-rank kernel time 2753.6 ms vs wall 3220.9 ms = 0.855).")
    L.append("- **THE CUSTOM AR IS LIVE - IT IS *NOT* UNWIRED.** D126 resolved the D117 hipIpc item as a")
    L.append("  single-process harness artifact. The fork's AR engages at world=4 in the TP4 serve")
    L.append("  (`rdna_ar: one-shot all-reduce active` x8 = 2 handles x 4 ranks, <=64 KB, which covers")
    L.append("  the 20 KB dominant message). In-server A/B: 47.70 tok/s with AR vs 45.37 without,")
    L.append("  byte-identical output (~+4%). Any older text saying otherwise is superseded by")
    L.append("  D142 addendum 3.")
    L.append("- **CURRENT COMPASS -> PHASE 5 (optimisation), chosen from measured TP4 data, not the V620")
    L.append("  ladder by analogy.** Baseline is **~47.7 tok/s** at MTP=0 (CORRECTED - the 49.04 originally")
    L.append("  recorded was a HIGH OUTLIER at the top of a 46.946-48.017 span; see D143 addendum), so the")
    L.append("  gap to G6 (>=50) is **~4.6%**, not ~1.9%, and the 60-62 parity target is further off.")
    L.append("  Whole-serve noise floor is ~1%, so only >2% effects are adoptable. Ranked targets:")
    L.append("  1. **NEXT TARGET - dense GEMV geometry (gemm_dense 24.3%)**: `gemv_f16_rdna2_<8,1>` alone is")
    L.append("     1253 ms / 50,691 launches (~24.7 us each); poor arithmetic intensity, so geometry/tile")
    L.append("     tuning is the lever. D143 ranks it the highest-headroom AND lowest-risk code target.")
    L.append("  2. **elementwise 11.8% across 303,380 launches** - the graph-boundary / torch elementwise")
    L.append("     residue; launch-count-dominated, so fusion is the lever.")
    L.append("  3. **moe_int4 19.8%** - includes **`moe::topkGating` at 449 ms (4.1% of all kernel time)**, a")
    L.append("     pure routing overhead. NOTE: MoE *tile-config* tuning is CLOSED NEGATIVE (D144: the tuned")
    L.append("     config measured -47.7% in situ), so only non-tile approaches (e.g. topkGating itself)")
    L.append("     remain, and they are not yet ranked.")
    L.append("  4. **collectives 21.0% of KERNEL time but only ~4% of WALL** - rank LAST despite owning the")
    L.append("     single largest kernel (`rdna_ar_oneshot`, 1741 ms / 49,664 launches), because the four")
    L.append("     ranks overlap. The AR is already live and measured.")
    L.append("- **Closed routes (do not re-open without new evidence):** MoE Triton tile-config tuning")
    L.append("  (D144, -47.7% measured, `VLLM_TUNED_CONFIG_FOLDER` deliberately UNSET); the cheap")
    L.append("  `--max-num-batched-tokens` lever (D143 addendum, flat inside the noise floor); Ray-based")
    L.append("  MoE tuning (actor workers segfault on this stack; the ray-free replacement works but its")
    L.append("  output was rejected).")
    L.append("- **Open items:** a reverse A/B (AR off->on) to firm the ~4% AR figure; Phase 0 snapshot")
    L.append("  artifacts so the baseline is reconstructable; and note **G4's first-64-token golden match")
    L.append("  stays UNEVALUABLE** until S3 generates golden traces - no amount of TP4 work fixes that.")
    L.append("- **Operator/environment notes:** `iommu=pt` added to <host>'s cmdline (RCCL warned of")
    L.append("  instability without it); model assets and <container>'s rootfs moved HDD -> NVMe, cutting cold")
    L.append("  load from ~399 s to 72.7 s; `<pool>/<subvol>` retained as rollback.")
    L.append("")
    L.append("## Plan flexes & pivots (curated history, beyond the task tracker)")
    L.append("")
    L.append("Every row is a departure from the original Rev 4/5 course, the driver behind it, and its")
    L.append("disposition. Full context lives in DECISIONS.md; this table is the narrative summary.")
    L.append("")
    L.append("| # | When | Plan element | Flex / pivot | Driver | Disposition |")
    L.append("|---|---|---|---|---|---|")
    flexes = [
        ("D005", "S1", "Power budget", "H1 capped at 150 W/GPU (operator custom answer)", "operator", "accepted; all measurements at the cap"),
        ("D009", "G0", "Hardware identity", "Card is a Radeon Pro Vega II (gfx906, <device-id>), not an MI50", "measurement", "gfx906:xnack- is the target; MI50 naming dropped"),
        ("D011/D014", "G1", "Toolchain route", "hipBLASLt/rocBLAS gfx906 gaps on 7.2.4 -> mixa3607 TheRock 7.14-gfx906 apt stack (torch 2.13.0+gfx906, triton 3.6.0+gfx906 source build)", "measurement", "accepted; the fork's tarball route not needed (N-B2)"),
        ("D016/D018/D019", "N-E6/G2.2", "Signalling scope", "No single-GPU race window demonstrable; ordering clause closed WITH RESIDUAL to M0.7 [ABS]", "measurement", "G2.2 single-GPU portion closed; peer clause deferred"),
        ("D021", "Track M", "Fabric", "No PEX88096 switch yet; 3 more cards delayed", "hardware", "multi-GPU work deferred; Track S re-scoped to single-GPU prep"),
        ("D023/D024", "Whole WO", "Work order revision", "V620 optimizations adopted; Rev 5 supersedes Rev 4 (reference impl confirmed)", "operator", "Rev 5 governs; I1-I10 carry forward"),
        ("D026", "N-C2", "Port strategy", "PORT-MAP: transfer-vs-redesign split; 15/17 UNVERIFIED resolved", "analysis", "transfer-as-is items identified; wave64 deltas enumerated"),
        ("D031", "N-D3", "All-reduce validation", "Concurrent-kernel uncached-flag visibility unreliable single-GPU -> protocol validation moves to the 4-card box (M0/M2)", "measurement", "reduce loop validated bit-exact; protocol is wave-agnostic"),
        ("D033", "N-C7", "Port tree base", "Port built on the leapdragon fork (branch mi50/qwen38-flash-next-gfx906)", "operator", "vllm/ tree live"),
        ("D035", "N-C7", "Test methodology", "rocBLAS fp32-GEMV segfault on gfx906 -> fused-op refs moved to CPU float64", "measurement", "harness adaptation; kernel verdicts unaffected"),
        ("D037", "PLE", "Offload data path", "CUDA-IPC device handoff incoherent on gfx906/VFIO -> PLE must use the CPU-pinned result path", "measurement", "design constraint recorded; serving path already uses it"),
        ("D039", "Serve scope", "Single-GPU end-to-end", "Full 73 GB AWQ cannot fit one 32 GB card -> 8-layer full-shape SURROGATE; shape_profile full, NOT I5 evidence", "operator", "surrogate scope approved"),
        ("D042/D051", "S3", "Oracle precision", "fp32 reference exceeds 48 GB -> fp16 oracle carries ~3e-4 rounding (same as the N-D1 floor)", "hardware", "caveat recorded; token-level T1 unaffected"),
        ("D044", "N-E1", "Ceiling of record", "Original read-stream 327.6 GB/s was a low-occupancy artifact -> corrected to ~810 GB/s (kernel-style probe)", "measurement", "N-E1 figures superseded; lm_head 786 GB/s = 97% of the ceiling"),
        ("D048-D052", "Am. 001", "Acceptance metric", "tok/s cannot separate engine gains from acceptance drift -> steps_per_second is the primary metric; I5 replaced; schema v2; G6/O6", "operator", "landed; acceptance.py is the only verdict path"),
        ("D053/D054", "Serve", "QSA attention", "triton 3.6.0+gfx906 cannot compile the fused qk-norm-rope-gate kernel -> eager reference path on gfx906", "measurement", "fusion disabled on gfx906 (Track-O: restore)"),
        ("D054", "S3", "Golden trust", "'Incoherent' golden text was the truncated model's REAL output - the GPU port reproduces it exactly (independent cross-check)", "measurement", "golden established as oracle (D3 + T1 + boundary flip)"),
        ("D056/D058", "S3/T2", "Per-layer drift", "Fork's delayed-combine restructure makes naive per-layer values non-comparable -> aligned FINAL-hidden comparison (consistent ~1e-2, spikes ~2e-1 from fused-kernel rounding)", "analysis", "T1 remains the path-level evidence"),
        ("D057/D059", "N-E4", "Model-level graphs", "Pull-back to the surrogate: graph lever CONFIRMED ~3.7x steady-state BUT output garbled under graphs", "operator + measurement", "D060: inductor miscompile was the garble source, not graphs"),
        ("D060", "N-E4", "Compile on gfx906", "Inductor compile-only garbles identically (miscompile) -> graphs-WITHOUT-compile is correct at ~3.3x; compile OFF on gfx906", "measurement", "N-E4 DONE (3.3x correct); compile enablement = Track O bisect"),
        ("D063-D067", "Pre-cards", "Push list", "M-track harness, tp4_rank0 scaffold, N-E7 routing skew (~1.28), N-E8 fixed cost (~15-20us), MoE-triton verified, bookkeeping", "operator/Claude", "all landed; tp4_rank0 measurements await a window"),
        ("D068-D072", "Switch", "PEX88096 install", "GPUs 'drop after boot' misread (vfio id-table); real issue = BIOS bus-window allocation; x8x8 unlocked it", "measurement", "switch x16-up + MI50 at <pci>; STOP-A answered (D071)"),
        ("D073-D074", "STOP-A", "ACS disposition", "pcie_acs_override only fixes grouping; the SILICON clear (setpci) is required and is ephemeral (rescan/reboot re-asserts)", "operator review", "PROVISIONAL: routing unverified until M0's bandwidth measurement; clear-pex-acs.service unit"),
        ("D075-D078", "Switch", "Link widths", "Upstream x8 (x8x8 required - extender 2x8i; x16 mode fails enumeration, D077); MI50 is Gen3 x16 (its max)", "measurement", "both quantified as non-issues (D078); G3 at M0 is the determination"),
        ("D103", "M0/G3", "Guest P2P", "2 cards live; pre-flight done (150W both, ACS cleared+sticking) but NO guest-visible P2P: canAccessPeer=0 (self incl), EnablePeerAccess fails, hipIpcOpenMemHandle fails, RCCL 2-dev segfaults; memcpyPeer ~6.2 GB/s host-bounce", "measurement", "fork rdna_allreduce + RCCL TP non-functional in the VFIO guest (QEMU hides the switch behind per-device root ports; 4 cards will not change it); transport direction = operator decision (multifunction re-presentation / host-staged M2 / bare-metal <source-host>)"),
        ("D104/D105", "M0/G3", "P2P deep-dive", "Config greps: P2P support EVERYWHERE (both kernels y; amdgpu.pcie_p2p=Y). RCCL 'segfault' = 7.2.4/7.14 runtime mix -> works ~63us/op on 7.14. Emulated-switch: pci_p2pdma_distance=4 both ways but KFD links still empty (UBSAN in amdgpu_amdkfd_get_pcie_bandwidth_mbytes suspect). GPUs PSP-wedged mid-experiment; <source-host> power cycle cleared it", "measurement + operator", "self-pair canAccessPeer=0 corrected (documented); STOP-D reworded to the PHYSICAL path (not fired); option (d) LXC on <source-host> added; box healthy on restored hostpci config (D105); decision pending: multifunction retest / host-staged RCCL / LXC"),
        ("D106", "M0/G3", "UBSAN root cause + RCCL floor", "Zero pcie link masks in passthrough confirmed (kern.log: shift exponent -1 at amdgpu_amdkfd.c:604); fix = amdgpu.pcie_gen_cap/pcie_lane_cap params or HWE kernel. RCCL 2-rank curve banked: ~56us overhead, 20KB 77.4us -> host path misses G6 at 4 ranks (95-160us/op projection); option (b) collapsed to RCCL + --disable-custom-all-reduce as a floor", "operator + measurement", "multifunction variant DROPPED (link caps, not ancestry); step-3 = params or HWE with clean reboot; step-4 = LXC on <source-host>; vfio.conf ids= parked until transport settled"),
        ("D108/D109", "M0/G3", "LXC P2P measurement", "Host KFD P2P links WORK (canAccessPeer=1, Enable OK - first ever); kernel peer store POISONS gfx906 writer (D108 wedge); SDMA hipMemcpyPeer measured 28.5 GB/s symmetric at 256 MB (byte-exact, ~90% of Gen4 x16 ceiling)", "measurement", "G3 answered on the host/LXC path - real switch P2P, beats the fork's 14.3/5.7; M2 adopts copy-based transport; deployment decision (LXC vs VM) is binding"),
        ("D110", "M0/G2.2/M2", "Post-D109 follow-ups", "SDMA peer-copy latency 11.8us@20KB (G5 point); 28.5GB/s = 1.8x upstream ceiling (switch-internal proof); UNCACHED kernel peer stores WORK (D108 poison was memory type) -> fork AR shape viable; N-E3 q2=1.89x on host; D037 partial", "operator + measurement", "kernel-store verdict reversed (D109 premature); phys-bits=42/43 is the stock lever (VM stays closed on merit); ACS PROVISIONAL->RESOLVED; M2: test kernel-store AR with UNCACHED staging, copy path not settled"),
        ("D112", "M0/deploy", "TP2 on the host path", "TP2 (2 GPUs, EP, PLE per-rank, torch.distributed over working host P2P) WORKS - first multi-GPU TP run of the port anywhere. Blocker was container RAM (8 GB OOM-killed a TP worker; PLE 30 GB prefault + 2 workers) -> 40 GB. Golden-like output (flip ~tok 11 vs 14 at TP1 = TP fp16 rounding). In-situ eager per-layer anchor 2.69 ms/layer incl. collectives+PLE (46.5 tok/s; batch-4 118 tok/s).", "measurement", "48-layer extrapolation now has a measured anchor; TP2->TP4 = one-variable projection (D065 1.28 skew); graphs-mode TP2 = follow-up"),
        ("D113", "M0/deploy", "Per-layer anchor decomposition", "TP2 eager: per_layer 2.35 ms + fixed 2.7 ms/step (4L vs 8L); scaling TP1->TP2 = 0.70x aggregate (NEGATIVE at 8L surrogate scale); graphs 2.9x at TP2 (133 tok/s); 48L eager ~115 ms/token at TP2-width", "measurement", "naive 2.69 ms/layer overstated ~14%; TP2->TP4 scaling is the dominant unknown and looks worse than clean halving; TP4 RAM ~46-50 GB collides with llama-in-LXC"),
        ("D114", "Whole WO", "Deployment decision", "LXC/host on <source-host> is THE target; VFIO dropped (guest P2P impossible, D107); transport decision closed; M0/M0.7/M1/M2 host-path items unblocked; llama no-home during M2-M4", "operator + other dev", "agreed; tracker rows re-scoped to 2-card host-path execution; direction review added (handoff Step 5)"),
        ("D115", "M0/Step 1", "Kernel/bubble probe", "~50 kernels/layer (48L ~2,400/step); torch-elementwise 43% of launches (gfx906 residue beyond the firing glue fusion); dispatch bubble ~7.7 ms/token eager = ~19us x ~410 kernels, removed by graphs", "measurement", "LAUNCH-BOUND confirmed; trace-justified Step 2 = cut the torch-elementwise soup (then qk-norm-rope, int8 dense)"),
        ("D116", "Step 3", "48L TP2 attempt", "73 GB AWQ TP2: no-offload OOM at expert-weight creation (~36.5 GB/rank); UVA offload (--cpu-offload-gb 20) hits a second blocker - PLE worker cannot load the full-model weight layout (_groupby_prefix)", "measurement", "exact VRAM deficit + PLE-worker full-model blocker recorded; surrogate profile = baseline; 48L needs the PLE-worker fix"),
        ("D117", "M2/Step 4", "M2 AR validated", "Wave64 one-shot all-reduce (fork T44 protocol, UNCACHED peer staging + flags): 30.7 us/op @ 20 KB world=2 on the 2 host GPUs, correct; hipIpcOpenMemHandle asymmetric (dev1->dev0 ok, dev0->dev1 fails)", "measurement", "meets the fork 33 us target; multi-process in-vLLM wiring remains (4-rank), routing around the hipIpc asymmetry"),
        ("D118-D121", "Step 2", "T46 closure verdict", "gfx906 ~50 kernels/layer vs fork 37 (real gap); glue fires; norms+QSA already triton-fused (layer_norm_fwd, _qsa_*); vllm_c norm priority = non-lever (identical counts); residual = ~22 torch-elem launches/layer", "measurement", "qk-norm-rope/int8/norm-fusion are NOT the gfx906 levers; next = trace_attr frame attribution of the elementwise residue, then fuse the largest sites"),




        ("D132", "M0/Step2", "48L graphs profile", "dense_gemv 53.7% of GPU time at 48L under graphs (fused_glue 26.9%, moe 13.2%, torch_elem <1%); dense offload-inflated ~20x (UVA zero-copy fetch); graphs do NOT remove the host-side offload stalls", "measurement", "confirms the D131 ranking; N-D5 targets the dominant term; offload cost hides in the dense kernels + host stalls"),
        ("D133-D136", "G6", "Task-1 microbenchmark", "dense 12-shape M4 0.704ms vs V620 1.43ms (~2.0x MI50); lm_head 451us vs 1.28ms fp16 (2.84x) and 640us int8 (1.42x); fused glue M-invariant bandwidth-bound (61-158us); MoE pair 109us @M1 vs 98us V620 (1.11x); QSA/GDN negligible; MTP0 parity ACHIEVABLE", "measurement", "memory-bound bulk (dense+glue ~81% GPU time) favors MI50 HBM; clock-bound MoE near-parity; N-D5 int8 rationale weakened; remaining V620-advantage candidates = MTP head + per-step fixed cost"),
        ("D137", "G6/M2", "Token accounting", "W = 393.84 ms/token (48L TP2 graphs+offload, med of 3, 2.54 tok/s); K/W ~91% (profiler); independent busy% UNAVAILABLE (flashed-card SM counter never leaves 0); Case A provisional ~9% residual; PLE/scheduler/sampling buckets unmeasured", "measurement", "60-62 t/s MTP0 plausible-but-unproven; dense_gemv ~49% of wall is offload-inflated - shrinks with cards 3-4; PLE/CPU instrumentation is the next accounting step"),
        ("D138", "G6/M2", "Offload-stall dominant", "D133+D132+D137 chain: resident dense GEMV excellent (816 GB/s), offload inflates it ~20x (~193 vs ~9.5 ms/token), the inflated family is ~49% of the 393.84 ms/token wall; K/W ~91% = kernel intervals not idle bubble; PLE deferred; cards 3-4 = the next experiment (128 GB resident TP4)", "analysis", "2.54 t/s TP2 must NOT be read as an MI50 silicon estimate; offload removal implies ~210 ms/token (~4.75 t/s, 1.87x) at TP2; another bottleneck may wait underneath - normal peeling; TRAPS.md created"),
        ("D111", "M0/deploy", "Stack validation on the host/LXC path", "Full surrogate stack (<vm> venv+tree+surrogate+PLE, bind-mounted, no rebuild) serves on the host GPUs: single-GPU reproduces the golden exactly through tok 14 then the documented boundary flip. Container env fixes: python3-dev, amdsmi-preinit sitecustomize (else vLLM 'Failed to infer device type'), cwd vs editable-vllm shadowing.", "measurement", "PASS - the port tree works on the host/LXC environment; <vm>-era numerical behavior reproduced"),




    ]
    for row in flexes:
        L.append("| " + " | ".join(row) + " |")
    L.append("")
    L.append("**Driver legend:** operator (binding amendment/decision) - measurement (a finding changed the")
    L.append("course) - hardware (physical reality) - analysis (port/architecture reasoning).")

    # ============================================================================================
    # 2026-09-18 expert-review execution (D148) and the final MTP2 selection (D149).
    #
    # These two sections were originally APPENDED BY HAND to PROGRESS.md by the reviewing engineer,
    # which meant the next `update_progress.py` run silently deleted them - the same failure mode as
    # the hand-edited status_update block fixed earlier. They are emitted from here now so the
    # generated page is the whole page. Text is kept verbatim, including the measured table.
    # ============================================================================================
    L.append("")
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 2026-09-18 — Expert-review execution (D148)")
    L.append("")
    L.append("Validated preset deployed on <container>: approximately 56 decode tok/s at 150 W/card, with "
             "effective PP approximately 658 tok/s at 512 tokens and 851 tok/s at 1536 tokens (see the "
             "report for exact configurations and metric definitions). Selected corrected prefill MoE "
             "tiles, mask-aware top-10 routing and a 2048-token chunk budget. NUMA did not show a speed "
             "gain; default all-reduce policy retained. MTP, TunableOp and INT8 remain off. Further "
             "experiments stopped at the operator's requested approximately 10% additional decode-gain "
             "threshold. Temporary ARC changes reverted; healthy service and launch/rollback "
             "instructions saved. Full results, numerical checks, limitations and canceled items: "
             "[TUNING-20260918.md](TUNING-20260918.md).")
    L.append("")
    L.append("")
    L.append("---")
    L.append("")
    L.append("## 2026-09-18 — Final MTP2 configuration and three-run long-context benchmark")
    L.append("")
    L.append("- Date: 2026-09-18 UTC.")
    L.append("- Supersedes D148's MTP0 operating choice following the explicit request to leave MTP2 "
             "and optimized PP enabled.")
    L.append("- Running: TP4+EP, 150 W/card, MTP2, tuned prefill MoE tiles and MI50 router, 2048-token "
             "chunk budget, 32768-token context. TunableOp and dense INT8 remain off. <container> port 8002, "
             "PID <pid>.")
    L.append("- Measured medians of three scored requests per exact prompt length, two warmups each, "
             "128 generated tokens, one active request, zero cached prompt tokens:")
    L.append("")
    L.append("| Prompt tokens | Median effective PP | Median first-token latency | Median decode | Decode range |")
    L.append("|---:|---:|---:|---:|---:|")
    L.append("| 1,000 | 641.9 tok/s | 1.558 s | 60.34 tok/s | 60.12–60.35 tok/s |")
    L.append("| 10,000 | 806.9 tok/s | 12.393 s | 61.22 tok/s | 39.02–65.35 tok/s |")
    L.append("| 30,000 | 805.1 tok/s | 37.263 s | 57.34 tok/s | 57.00–61.83 tok/s |")
    L.append("")
    L.append("- Synthetic repeated prose corpus. Long-context continuations varied at temperature "
             "zero; 10K decode spread is material. These results do not establish long-context quality "
             "or deterministic output.")
    L.append("- Post-run smoke: 11/12, same packing failure as reference. Health 200. No further "
             "tuning experiments started.")
    L.append("- Default `tools/review_20260918/scripts/launch.sh balanced` now starts MTP2/32K; `mtp0` "
             "retains optimized MTP0/2K; `reference` and `stop` remain available.")
    L.append("- Details: [MTP2-FINAL-20260918.md](MTP2-FINAL-20260918.md), raw requests and summary "
             "under `tools/review_20260918/mtp2_final_1k_10k_30k/`, updated presets and final state, "
             "and `MI50_MTP2_EVIDENCE.tar.gz`.")

    (ROOT / "PROGRESS.md").write_text("\n".join(L) + "\n")
    print("PROGRESS.md regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
