"""verify_bootstrap.py — machine-checkable acceptance checker for the project
bootstrap (Work Order Rev 4, section 5). Exits 0 iff every bootstrap predicate
holds on the committed tree; exits 1 otherwise, printing each failed check.

Run from anywhere:  python3 harness/verify_bootstrap.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def _registry_task_ids() -> list:
    try:
        reg = json.load(open(ROOT / "config" / "tasks.json"))
        return [t["id"] for t in reg.get("tasks", [])]
    except Exception:
        return []

# The Rev 5 registry is the source of truth (Rev 4's P/S task set was replaced
# by the N-A..N-E lanes); expectations are derived, not hard-coded.
EXPECTED_TASK_IDS = _registry_task_ids()
ALLOWED_STATUSES = {"pending", "blocked-on-human", "blocked-on-hardware",
                    "running", "done", "failed", "deferred"}

REQUIRED_DIRS = [
    "config", "harness", "golden", "kernels/gfx906", "vllm",
    "tools/gfx906", "results", "reports",
]
REQUIRED_FILES = [
    "WORK_ORDER_REV4.md",
    "README.md",
    "DECISIONS.md",
    "config/tasks.json",
    "config/tolerances.yaml",
    "config/environment.lock",
    "harness/results_schema.json",
    "harness/results.py",
    "harness/run_task.py",
    "harness/env_fingerprint.py",
    "harness/verify_bootstrap.py",
    "harness/verify.py",
    "harness/README.md",
    "tests/bootstrap_negative.sh",
]
ARTIFACT_DIRS_WITH_README = [
    "golden", "kernels/gfx906", "vllm", "tools/gfx906", "results", "reports",
]

failures: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    if ok:
        print(f"  PASS  {name}")
    else:
        print(f"  FAIL  {name}" + (f" — {detail}" if detail else ""))
        failures.append(name)


def verify_tasks_registry() -> None:
    path = ROOT / "config" / "tasks.json"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        check("tasks.json parses", False, str(exc))
        return
    ids = [t.get("id") for t in data.get("tasks", [])]
    missing = [i for i in EXPECTED_TASK_IDS if i not in ids]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    check("tasks.json contains every work-order task id exactly once",
          not missing and not dupes,
          f"missing={missing} dupes={dupes}")
    # Rev 4 bootstrap-phase expectations (P1/P2/P3 blocked-on-human) are
    # historical: P1 resolved (D020), the P/S tracks were replaced by the
    # N-lanes in Rev 5. The registry's own status vocabulary is the check.
    bad_status = [t.get("id") for t in data.get("tasks", [])
                  if t.get("status") not in ALLOWED_STATUSES]
    check("all task statuses are valid", not bad_status, str(bad_status))
    check("gates present", isinstance(data.get("gates"), list) and len(data["gates"]) >= 6)
    check("stops present", isinstance(data.get("stops"), list) and len(data["stops"]) >= 5)


def verify_tolerances() -> None:
    path = ROOT / "config" / "tolerances.yaml"
    try:
        import yaml  # PyYAML (present at bootstrap; required from S3 onward)
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception as exc:
        check("tolerances.yaml parses (PyYAML)", False, str(exc))
        return
    tiers = data.get("tiers", {}) if isinstance(data, dict) else {}
    check("tolerances.yaml declares t1/t2/t3",
          all(t in tiers for t in ("t1", "t2", "t3")))
    # Only the tolerance-bearing keys must be UNSET at bootstrap. Schema
    # constants copied from the work order (e.g. t2.inputs == 8, the S3
    # '>= 8 fixed inputs' acceptance) are not tolerances and may be numeric.
    tolerance_keys = {"abs_tol", "rel_tol", "drift_budget_per_layer"}
    numeric = []
    for tier, body in tiers.items():
        if not isinstance(body, dict):
            continue
        for key, value in body.items():
            if key in tolerance_keys and isinstance(value, (int, float)) \
                    and not isinstance(value, bool):
                numeric.append(f"{tier}.{key}={value}")
    check("tolerances.yaml has NO numeric tolerance values at bootstrap "
          "(values declared at S3, frozen under I4/H6)", not numeric, str(numeric))
    undeclared = [t for t in ("t1", "t2", "t3")
                  if tiers.get(t, {}).get("status") != "undeclared"]
    check("all tiers status == undeclared", not undeclared, str(undeclared))


def verify_env_lock() -> None:
    path = ROOT / "config" / "environment.lock"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        check("environment.lock parses", False, str(exc))
        return
    check("environment.lock was generated by the harness",
          str(data.get("_generated_by", "")).startswith("harness/env_fingerprint.py"),
          str(data.get("_generated_by")))
    needed = ["rocm_version", "torch_version", "gfx_target", "guest_kernel",
              "pve_version", "gpu_count"]
    absent = [k for k in needed if k not in data]
    check("environment.lock carries the fingerprint fields", not absent, str(absent))


def verify_results_rows() -> None:
    """Permanent invariant (I3 + schema): every run row in results/ conforms to
    results_schema.json. (The bootstrap-time 'results/ is empty' predicate was
    superseded once S0 wrote real rows; artifacts like byte_budget.jsonl and
    gpu_probe.jsonl are task artifacts, not run rows.)"""
    import sys as _sys
    _sys.path.insert(0, str(ROOT / "harness"))
    import results  # noqa: E402
    bad: list[str] = []
    ids = [t["id"] for t in json.loads((ROOT / "config" / "tasks.json").read_text())["tasks"]]
    for tid in ids:
        path = ROOT / "results" / f"{tid}.jsonl"
        if not path.exists():
            continue
        try:
            for row in results.read_rows(tid):
                results.validate_row(row)
        except Exception as exc:
            bad.append(f"{tid}: {exc}")
    check("all run rows in results/ validate against results_schema.json (I3)",
          not bad, "; ".join(bad[:5]))


def verify_oracle_stub_fails() -> None:
    proc = subprocess.run(
        [sys.executable, str(ROOT / "harness" / "verify.py")],
        capture_output=True, text=True, timeout=30,
    )
    check("harness/verify.py (S3 oracle stub) exits non-zero until S3 lands",
          proc.returncode != 0, f"exit={proc.returncode}")


def verify_git() -> None:
    head = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "HEAD"],
                          capture_output=True, text=True, timeout=10)
    check("git repo has an initial commit", head.returncode == 0)
    status = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"],
                            capture_output=True, text=True, timeout=10)
    check("working tree is clean", status.returncode == 0 and not status.stdout.strip(),
          status.stdout.strip()[:200])


def _schema_valid_row(thermally_valid, shape_profile):
    """A schema-valid v2 row (all required fields present, plausible values)."""
    import uuid
    return {
        "run_id": uuid.uuid4().hex, "task_id": "T", "git_commit": "deadbeef",
        "dirty_flag": False, "exit_code": 0, "wall_seconds": 10.0,
        "timeout_s": 600.0, "notes": "", "schema_version": 2,
        "rocm_version": "not measured", "torch_version": "not measured",
        "triton_commit": "not measured", "vllm_commit": "not measured",
        "kernel_version": "not measured", "gfx_target": "gfx906:xnack-",
        "guest_kernel": "not measured", "pve_version": "not measured",
        "gpu_count": 1, "tp": 1, "ep": 1, "mtp": 0, "power_cap_w": 150,
        "observed_power_w": None, "gpu_clock_mhz": None, "hbm_clock_mhz": None,
        "temp_c": None, "soak_seconds": 0, "context": None, "gen_tokens": None,
        "repeat_index": 0, "tokens_per_second": 1.0, "prefill_tps": None,
        "ttft_ms": None, "kernel_config": None, "correctness_hash": None,
        "steps_per_second": 1.0, "accepted_tokens_per_step": None,
        "forward_steps": 10, "decode_wall_seconds": 10.0,
        "shape_profile": shape_profile, "graphs": "off", "dtype": "float16",
        "ple_source": "int4_sidecar", "ple_offload": True,
        "thermally_valid": thermally_valid, "clock_deviation_pct": 0.0,
        "timed_out": False, "tp4_projection_factor": None,
    }


def verify_acceptance_refusals():
    """D3 bootstrap negative controls (D048/I5): the acceptance calculator must
    refuse (a) a schema-valid row with thermally_valid false, and (b) a
    full-profile row submitted for a TP4 decision. Schema-valid rows that the
    oracle has not rejected are not known to enforce I5."""
    import importlib.util
    import tempfile

    spec = importlib.util.spec_from_file_location("acceptance", ROOT / "harness" / "acceptance.py")
    acc = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(acc)

    def mk(rows):
        fd = tempfile.NamedTemporaryFile("w", suffix=".jsonl", delete=False)
        for r in rows:
            fd.write(json.dumps(r) + "\n")
        fd.close()
        return fd.name

    good = [_schema_valid_row(True, "tp4_rank0") for _ in range(15)]
    # (a) after-side thermally invalid
    bad_thermal = good + [_schema_valid_row(False, "tp4_rank0")]
    rc = acc.verdict(good, bad_thermal, tp4=True, mtp_on=False)
    check("acceptance refuses thermally_valid:false rows", rc == 2)
    # (b) full-profile rows submitted for a TP4 decision
    bad_full = [_schema_valid_row(True, "full") for _ in range(15)]
    rc = acc.verdict(bad_full, [_schema_valid_row(True, "full") for _ in range(15)],
                     tp4=True, mtp_on=False)
    check("acceptance refuses full-profile rows for a TP4 decision", rc == 2)
    # (c) v1 rows inadmissible
    v1 = [_schema_valid_row(True, "tp4_rank0") for _ in range(15)]
    v1[<bus>]["schema_version"] = 1
    rc = acc.verdict(v1, [_schema_valid_row(True, "tp4_rank0") for _ in range(15)],
                     tp4=True, mtp_on=False)
    check("acceptance refuses schema_version:1 rows", rc == 2)
    # (d) N < 15 refused
    rc = acc.verdict(good[:5], good, tp4=True, mtp_on=False)
    check("acceptance refuses N < 15", rc == 2)


def main() -> int:
    print(f"verify_bootstrap: {ROOT}")
    for d in REQUIRED_DIRS:
        check(f"dir exists: {d}", (ROOT / d).is_dir())
    for f in REQUIRED_FILES:
        check(f"file exists: {f}", (ROOT / f).is_file())
    for d in ARTIFACT_DIRS_WITH_README:
        check(f"artifact dir README: {d}/README.md",
              (ROOT / d / "README.md").is_file())
    verify_tasks_registry()
    verify_tolerances()
    verify_env_lock()
    verify_results_rows()
    verify_oracle_stub_fails()
    verify_acceptance_refusals()
    verify_git()
    print(f"\nverify_bootstrap: {'ALL PASS' if not failures else f'{len(failures)} FAILURES'}")
    return 0 if not failures else 1


if __name__ == "__main__":
    sys.exit(main())
